# Generated by Django 2.2 on 2019-04-16 20:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=64)),
                ('code', models.CharField(db_index=True, max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('description', models.TextField()),
                ('price', models.DecimalField(db_index=True, decimal_places=3, default=0, max_digits=10)),
                ('currency', models.CharField(max_length=16)),
                ('guarantee', models.DecimalField(db_index=True, decimal_places=3, default=0, max_digits=10)),
                ('in_case', models.BooleanField(db_index=True, default=False)),
                ('image', models.ImageField(blank=True, max_length=512, null=True, upload_to='equipment/%Y/%m/%d/')),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Market',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=64)),
                ('url', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='SubGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=64)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipment.Group')),
            ],
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=64)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, max_length=512, null=True, upload_to='manufacture/%Y/%m/%d/')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipment.Country')),
            ],
        ),
        migrations.CreateModel(
            name='EquipmentMarketConnection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=512)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipment.Equipment')),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipment.Market')),
            ],
        ),
        migrations.AddField(
            model_name='equipment',
            name='manufacture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipment.Manufacturer'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='subgroup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipment.SubGroup'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='type_of',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipment.Type'),
        ),
    ]
