# Generated by Django 2.2 on 2019-04-20 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0002_auto_20190416_2058'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmentmarketconnection',
            name='market_url',
            field=models.CharField(default='', max_length=256),
        ),
    ]
