# Generated by Django 2.2.1 on 2019-05-01 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0003_equipmentmarketconnection_market_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equipmentmarketconnection',
            old_name='market_url',
            new_name='eq_in_market_url',
        ),
    ]
