# Generated by Django 2.2.1 on 2019-05-01 16:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personal_area', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featuredequipment',
            name='equipment_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='equipment.Equipment'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='featuredequipment',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
